[versions]
agp="8.10.1"
kotlin="2.0.21"
coroutine="1.10.2" # 1.7.3
core-ktx="1.16.0" # 1.13.0
appcompat="1.7.1" # 1.7.0
activity-ktx="1.9.0" # 1.9.0
lifecycle="2.9.0" # 2.9.0
preference-ktx="1.2.1" # 1.2.1
navigation="2.8.9" # 2.8.9
splashscreen="1.0.1" # 1.0.1

room="2.8.3" # 2.3.0
paging="3.3.2"
workmanager="2.9.1" # 2.9.1

material="1.13.0" # 1.12.0
constraintlayout="2.2.1" # 2.2.1
viewpager2="1.1.0" # 1.1.0
recyclerview="1.3.0" # 1.3.0
cardview="1.0.0"
shimmereffect="1.0.0"

apache-compress="1.28.0" # 1.27.1
gson="2.13.2" # 2.10.1
documentfile = "1.1.0"

junit="4.13.2"
android-test="1.7.0" # 1.6.2
junit-android="1.3.0" # 1.2.1
espresson="3.7.0" # 3.6.1

[libraries]
coroutine-core={ module='org.jetbrains.kotlinx:kotlinx-coroutines-core', version.ref='coroutine' }
coroutine-android={ module='org.jetbrains.kotlinx:kotlinx-coroutines-android', version.ref='coroutine' }

core-ktx={ module='androidx.core:core-ktx', version.ref='core-ktx' }
appcompat={ module='androidx.appcompat:appcompat', version.ref='appcompat' }
activity={ module='androidx.activity:activity-ktx', version.ref='activity-ktx' }
viewmodel={ module='androidx.lifecycle:lifecycle-viewmodel-ktx', version.ref='lifecycle' }
livedata={ module='androidx.lifecycle:lifecycle-livedata-ktx', version.ref='lifecycle' }
preference={ module='androidx.preference:preference-ktx', version.ref='preference-ktx' }

navigation-fragment={ module='androidx.navigation:navigation-fragment-ktx', version.ref='navigation' }
navigation-ui={ module='androidx.navigation:navigation-ui-ktx', version.ref='navigation' }

splashscreen={ module='androidx.core:core-splashscreen', version.ref='splashscreen'}

material={ module='com.google.android.material:material', version.ref='material' }
constraintlayout={ module='androidx.constraintlayout:constraintlayout', version.ref='constraintlayout' }
viewpager2={ module='androidx.viewpager2:viewpager2', version.ref='viewpager2' }
recyclerview={ module='androidx.recyclerview:recyclerview', version.ref='recyclerview' }
cardview={ module='androidx.cardview:cardview', version.ref='cardview' }
shimmereffect={ module='com.github.rahulstech:shimmer-android', version.ref='shimmereffect' }

room-runtime={ module='androidx.room:room-runtime', version.ref='room' }
room-compiler={ module='androidx.room:room-compiler', version.ref='room' }
room-ktx={ module='androidx.room:room-ktx', version.ref='room' }
room-paging={ module='androidx.room:room-paging', version.ref='room' }
room-test={ module='androidx.room:room-testing', version.ref='room' }

paging-runtime={ module='androidx.paging:paging-runtime', version.ref='paging' }
paging-runtime-ktx={ module='androidx.paging:paging-runtime-ktx', version.ref='paging' }

workmanager-runtime={ module='androidx.work:work-runtime-ktx', version.ref='workmanager' }
workmanager-test={ module='androidx.work:work-testing', version.ref='workmanager' }

apachec-compress={ module='org.apache.commons:commons-compress', version.ref='apache-compress' }
gson={ module='com.google.code.gson:gson', version.ref='gson' }
documentfile = { module="androidx.documentfile:documentfile", version.ref = "documentfile" }

junit={ module='junit:junit', version.ref='junit' }
junit-android={ module='androidx.test.ext:junit', version.ref='junit-android'}
android-runnner={ module='androidx.test:runner', version.ref='android-test' }
android-rules={ module='androidx.test:rules', version.ref='android-test' }
espresso={ module='androidx.test.espresso:espresso-core', version.ref='espresson' }

[plugins]
application={ id='com.android.application' }
library={ id='com.android.library' }
kotlin={ id='org.jetbrains.kotlin.android' }
kapt={ id='kotlin-kapt' }